export type LangKey = "ko" | "en" | "zh" | "ja";

export type BreedProfileKey =
  | "maltese" | "bichon" | "poodle" | "pomeranian" | "dachshund" | "mixed"
  | "shihTzu" | "chihuahua" | "yorkie" | "minpin" | "corgi" | "shiba"
  | "frenchie" | "pug" | "beagle" | "schnauzer" | "borderCollie" | "golden"
  | "labrador" | "samoyed" | "jindo" | "spitz" | "unknown";

type LocalText = Record<LangKey, string>;
type InstinctKey = "companion" | "social" | "puzzle" | "alert" | "earth" | "scent" | "herding" | "primitive" | "retrieve" | "working" | "individual";
type MissionKey = "microTricks" | "socialCircuit" | "hideFind" | "soundSearch" | "burrowBox" | "sniffTrail" | "treibball" | "choiceGame" | "tugRules" | "coolShort" | "fetchCarry" | "workingWalk" | "threeToyTest";
type ChewKey = "gentleSmall" | "softRotation" | "puzzleChew" | "scentChew" | "tugChew" | "independentChoice" | "flatFaceSafe" | "carryChew" | "varietyTest";
type CareKey = "dental" | "coat" | "back" | "heat" | "escape" | "voice" | "earsWeight" | "jointsWeight" | "herdingRest" | "observe";

export type BreedProfile = {
  energy: 1 | 2 | 3 | 4 | 5;
  focus: 1 | 2 | 3 | 4 | 5;
  independence: 1 | 2 | 3 | 4 | 5;
  instinct: InstinctKey;
  mission: MissionKey;
  chew: ChewKey;
  care: CareKey;
  insight: LocalText;
};

const l = (ko: string, en: string, zh: string, ja: string): LocalText => ({ ko, en, zh, ja });

export const breedProfiles: Record<BreedProfileKey, BreedProfile> = {
  maltese: { energy: 2, focus: 3, independence: 2, instinct: "companion", mission: "microTricks", chew: "gentleSmall", care: "dental", insight: l("보호자의 반응을 빠르게 읽는 소형 동반견이에요. 길게 지치게 하기보다 짧은 성공을 자주 만들어주세요.", "A small companion that reads people quickly. Favor frequent, short wins over exhausting sessions.", "善于观察主人的小型伴侣犬。与其长时间消耗，不如多安排短暂成功。", "人の反応をよく読む小型の伴侶犬。長時間より、短い成功を何度も作りましょう。") },
  poodle: { energy: 4, focus: 5, independence: 2, instinct: "puzzle", mission: "hideFind", chew: "puzzleChew", care: "coat", insight: l("문제 해결이 빠른 편이라 단순 반복은 금방 싫증날 수 있어요. 규칙을 조금씩 바꾸는 놀이가 잘 맞습니다.", "Quick problem-solvers can tire of repetition. Games with gradually changing rules are a strong fit.", "解决问题能力较强，容易厌倦单调重复。适合逐步变化规则的游戏。", "問題解決が速く、単純な反復には飽きやすい傾向。少しずつルールを変える遊びが向きます。") },
  mixed: { energy: 3, focus: 3, independence: 3, instinct: "individual", mission: "threeToyTest", chew: "varietyTest", care: "observe", insight: l("믹스견은 외모만으로 행동을 예측하기 어렵습니다. 세 가지 놀이를 시험해 ‘우리 아이의 선택’을 데이터로 남겨보세요.", "Appearance alone predicts little in mixed-breed dogs. Test three games and record your dog’s own choices.", "混种犬很难仅凭外貌预测行为。测试三种游戏，记录它自己的选择。", "ミックス犬は見た目だけで行動を予測しにくいもの。3種類の遊びを試し、その子の選択を記録しましょう。") },
  pomeranian: { energy: 3, focus: 4, independence: 3, instinct: "alert", mission: "soundSearch", chew: "gentleSmall", care: "voice", insight: l("작지만 주변 변화에 빠르게 반응하는 경계형 스피츠예요. 소리 뒤에 ‘찾기’를 연결하면 짖음 에너지를 놀이로 바꾸기 좋습니다.", "A small, alert spitz that notices change quickly. Pair sounds with a search task to redirect arousal into play.", "体型虽小但对环境变化十分敏锐。把声音与寻找任务连接起来，可将兴奋转为游戏。", "小柄でも周囲の変化に敏感なスピッツ。音の後に『探す』課題を入れ、興奮を遊びへ変えます。") },
  bichon: { energy: 3, focus: 3, independence: 1, instinct: "social", mission: "socialCircuit", chew: "softRotation", care: "coat", insight: l("사람과 함께하는 활동에서 동기가 잘 생기는 편이에요. 혼자 노는 연습도 아주 짧게 성공부터 쌓아주세요.", "Often motivated by shared activity. Build independent play from very short, successful intervals.", "通常更喜欢与人互动。独处玩耍应从很短且成功的时间开始。", "人と一緒の活動で意欲が出やすい犬種。ひとり遊びは短い成功から積み上げましょう。") },
  shihTzu: { energy: 2, focus: 2, independence: 2, instinct: "companion", mission: "coolShort", chew: "flatFaceSafe", care: "heat", insight: l("강한 운동보다 천천히 냄새를 맡고 쉬는 짧은 코스가 잘 맞아요. 더운 날에는 흥분을 올리는 놀이를 줄여주세요.", "Short, slow sniffing routes suit them better than intense exercise. Keep arousal lower in warm weather.", "比起剧烈运动，更适合缓慢嗅闻和休息的短路线。天气炎热时减少高兴奋游戏。", "激しい運動より、ゆっくり匂いを嗅いで休む短いコースが向きます。暑い日は興奮を上げすぎないでください。") },
  chihuahua: { energy: 2, focus: 3, independence: 4, instinct: "alert", mission: "choiceGame", chew: "gentleSmall", care: "dental", insight: l("작은 체구 때문에 안아 올리기 쉽지만, 스스로 거리를 선택하게 하면 경계 반응을 줄이는 데 도움이 됩니다.", "Their size makes picking them up tempting, but letting them choose distance can reduce defensive reactions.", "体型小容易被抱起，但让它自己选择距离，有助于减少警戒反应。", "小さいため抱き上げがちですが、自分で距離を選べるようにすると警戒反応を減らしやすくなります。") },
  yorkie: { energy: 4, focus: 4, independence: 3, instinct: "earth", mission: "burrowBox", chew: "tugChew", care: "dental", insight: l("겉모습은 작고 우아하지만 테리어의 탐색·추적 욕구가 살아 있어요. 파고 찾는 과제를 주면 집안 탐색이 줄어듭니다.", "Small and elegant, yet still a terrier with search-and-chase drive. Dig-and-find tasks can redirect household exploring.", "外表小巧优雅，但仍保留梗犬的探索与追踪欲望。挖掘寻找任务可转移室内探索。", "小さく優雅でも、テリアらしい探索・追跡欲求があります。掘って探す課題で室内探索を満たします。") },
  minpin: { energy: 5, focus: 4, independence: 4, instinct: "alert", mission: "hideFind", chew: "tugChew", care: "escape", insight: l("움직임이 빠르고 호기심이 강한 소형견이에요. 달리기만 시키기보다 찾기와 멈춤 신호를 섞어야 만족도가 높습니다.", "Fast-moving and curious. Mix searching and stop cues with movement instead of relying on running alone.", "动作快、好奇心强。不要只让它跑动，应把寻找与停止信号结合。", "動きが速く好奇心旺盛。走らせるだけでなく、探索と停止の合図を組み合わせます。") },
  corgi: { energy: 4, focus: 5, independence: 3, instinct: "herding", mission: "treibball", chew: "tugChew", care: "back", insight: l("움직이는 대상을 통제하려는 목양 성향이 놀이에 잘 드러나요. 공을 정해진 방향으로 미는 과제가 잘 맞습니다.", "Herding heritage often appears as a wish to control movement. Directed ball-pushing tasks are a natural match.", "牧牛本能常表现为控制移动目标。把球推向指定方向的任务很合适。", "動くものをコントロールしたい牧畜傾向が遊びに表れます。ボールを指定方向へ押す課題が向きます。") },
  shiba: { energy: 4, focus: 4, independence: 5, instinct: "primitive", mission: "choiceGame", chew: "independentChoice", care: "escape", insight: l("독립적인 선택 성향이 강해 강요하면 거부가 커질 수 있어요. 두 가지 대안 중 스스로 고르게 하면 협력이 좋아집니다.", "Strong independent choice can turn into resistance under pressure. Cooperation improves when offered two acceptable options.", "独立选择倾向较强，强迫可能增加抗拒。提供两个可接受选项让它自己选择。", "自立した選択傾向が強く、強制すると拒否が増えやすい犬種。2つの選択肢から自分で選ばせます。") },
  frenchie: { energy: 3, focus: 3, independence: 2, instinct: "companion", mission: "coolShort", chew: "flatFaceSafe", care: "heat", insight: l("사람과 하는 짧고 유쾌한 놀이가 잘 맞지만 흥분이 오래가면 호흡 부담이 커질 수 있어요. 자주 쉬어주세요.", "Short, playful interaction suits them, but prolonged excitement can strain breathing. Build in frequent rests.", "适合与人进行短暂有趣的互动，但长时间兴奋可能增加呼吸负担，应经常休息。", "人と短く楽しく遊ぶのが得意ですが、興奮が長いと呼吸負担が増えます。こまめに休みましょう。") },
  pug: { energy: 2, focus: 2, independence: 1, instinct: "social", mission: "coolShort", chew: "flatFaceSafe", care: "heat", insight: l("함께 있는 것 자체가 큰 보상이 되는 편이에요. 격한 놀이보다 짧은 냄새 찾기와 차분한 교감이 좋습니다.", "Company itself can be highly rewarding. Choose short scent searches and calm interaction over intense play.", "陪伴本身往往就是很大的奖励。比起剧烈游戏，更适合短暂嗅闻和安静互动。", "一緒にいること自体が大きな報酬。激しい遊びより、短い匂い探しと穏やかな交流が向きます。") },
  beagle: { energy: 5, focus: 3, independence: 4, instinct: "scent", mission: "sniffTrail", chew: "scentChew", care: "earsWeight", insight: l("냄새를 따라가는 동안 사람 신호가 잠시 ‘꺼진 것처럼’ 보일 수 있어요. 냄새 찾기 자체를 보상으로 사용하세요.", "Human cues can seem to disappear once a scent trail starts. Use access to sniffing as the reward itself.", "一旦开始追踪气味，可能像听不见人的信号。可把嗅闻本身作为奖励。", "匂いを追い始めると人の合図が届きにくく見えることがあります。嗅ぐこと自体を報酬にします。") },
  schnauzer: { energy: 4, focus: 4, independence: 3, instinct: "earth", mission: "soundSearch", chew: "tugChew", care: "voice", insight: l("작은 움직임과 소리에 민감한 작업견 성향이 있어요. 경계 후 보호자에게 돌아오는 루틴을 게임처럼 가르쳐주세요.", "Working-dog alertness can lock onto small sounds and movement. Teach a game-like routine of notice, then return to you.", "对细小声音和动作较敏感。把“发现后回到主人身边”训练成游戏。", "小さな音や動きに敏感な作業犬タイプ。気づいた後に飼い主へ戻る流れをゲームにします。") },
  borderCollie: { energy: 5, focus: 5, independence: 2, instinct: "herding", mission: "treibball", chew: "puzzleChew", care: "herdingRest", insight: l("달리기만 늘리면 체력만 더 좋아질 수 있어요. 정답을 생각하고 멈추는 과제가 반드시 함께 필요합니다.", "More running can simply build more stamina. Pair exercise with tasks that require thinking and settling.", "只增加跑动可能只会增强体力。必须同时安排思考答案和停止休息的任务。", "走る量だけ増やすと体力だけが上がることも。考えて止まる課題を必ず組み合わせます。") },
  golden: { energy: 4, focus: 4, independence: 1, instinct: "retrieve", mission: "fetchCarry", chew: "carryChew", care: "jointsWeight", insight: l("입으로 물건을 운반하는 행동이 자연스러운 리트리버예요. 빼앗기보다 ‘가져오기→놓기→교환’을 놀이로 만드세요.", "Carrying objects is natural retriever behavior. Turn it into bring, drop, and trade rather than grabbing items away.", "用嘴搬运物品是寻回犬的自然行为。把它变成“取回—放下—交换”的游戏。", "物を口で運ぶのが自然なレトリーバー。奪うより『持ってくる→離す→交換』を遊びにします。") },
  labrador: { energy: 5, focus: 4, independence: 1, instinct: "retrieve", mission: "fetchCarry", chew: "carryChew", care: "jointsWeight", insight: l("먹이와 물건 운반 동기가 강한 편이라 삼키지 않는 교환 규칙이 중요해요. 큰 장난감으로 성공을 쉽게 만드세요.", "Food and carrying motivation can be strong, so a no-swallow trade routine matters. Start with large, easy-to-manage toys.", "食物和搬运动机较强，因此需要建立不吞咽的交换规则。先用较大的玩具提高成功率。", "食べ物と運搬への意欲が強い傾向。飲み込まない交換ルールを、大きめの玩具から教えます。") },
  samoyed: { energy: 5, focus: 3, independence: 2, instinct: "working", mission: "workingWalk", chew: "tugChew", care: "heat", insight: l("함께 이동하고 소리로 표현하는 북방 작업견이에요. 목적 있는 산책과 당기기 규칙을 주면 에너지 출구가 생깁니다.", "A northern working dog built for shared movement and vocal expression. Purposeful walks and structured tug provide an outlet.", "北方工作犬，喜欢共同移动并用声音表达。目的性散步和有规则的拉扯可释放精力。", "一緒に移動し声で表現する北方作業犬。目的のある散歩とルール付きの引っ張り遊びが発散になります。") },
  jindo: { energy: 4, focus: 4, independence: 5, instinct: "primitive", mission: "choiceGame", chew: "independentChoice", care: "escape", insight: l("한 사람과의 신뢰와 독립적인 판단이 함께 나타나는 편이에요. 억지로 빼앗지 말고, 거리를 두고 교환을 제안하세요.", "Close trust and independent judgment often coexist. Avoid forced removal; offer trades with respectful distance.", "深厚信任与独立判断常并存。不要强行夺取，应保持距离提出交换。", "深い信頼と自立した判断が共存しやすい犬種。無理に奪わず、距離を保って交換を提案します。") },
  spitz: { energy: 4, focus: 4, independence: 3, instinct: "alert", mission: "soundSearch", chew: "softRotation", care: "voice", insight: l("환경의 작은 변화도 빨리 알리는 경계형 동반견이에요. 확인 후 매트로 돌아오는 ‘알림 종료’ 루틴이 유용합니다.", "An alert companion quick to announce small changes. A notice-then-return-to-mat routine helps close the alert loop.", "能迅速提醒环境细微变化。建立“确认后回垫子”的结束警戒流程。", "環境の小さな変化も知らせる警戒型。確認後にマットへ戻る『お知らせ終了』ルーティンが役立ちます。") },
  dachshund: { energy: 4, focus: 4, independence: 4, instinct: "scent", mission: "burrowBox", chew: "scentChew", care: "back", insight: l("땅속 사냥을 위해 냄새를 따라 파고드는 선택을 해온 견종이에요. 수건 굴이나 상자 찾기가 본능을 안전하게 풀어줍니다.", "Selected to follow scent underground. Towel tunnels and box searches offer a safer outlet for burrowing instincts.", "为追踪地下气味而培育。毛巾隧道和纸箱寻找能安全满足钻挖本能。", "地下の匂いを追うために発達した犬種。タオルのトンネルや箱探しで安全に本能を満たします。") },
  unknown: { energy: 3, focus: 3, independence: 3, instinct: "individual", mission: "threeToyTest", chew: "varietyTest", care: "observe", insight: l("견종을 몰라도 괜찮아요. 냄새·당기기·찾기 중 무엇을 먼저 고르는지 관찰하면 맞춤 가이드를 만들 수 있습니다.", "Not knowing the breed is fine. Observe whether scent, tug, or search is chosen first to personalize care.", "不知道犬种也没关系。观察它先选择嗅闻、拉扯还是寻找，即可逐步定制。", "犬種が分からなくても大丈夫。匂い・引っ張り・探索のどれを先に選ぶか観察しましょう。") },
};

export const breedGuideText = {
  ko: {
    tendency: "견종 경향", energy: "활동 욕구", focus: "과제 집중", independence: "독립 선택", low: "낮음", high: "높음",
    mission: "오늘의 10분 미션", chew: "물어뜯기 대체 전략", care: "생활 체크 포인트", sources: "이 가이드의 근거", close: "근거 접기",
    note: "견종은 출발점일 뿐입니다. 같은 견종에서도 나이·경험·건강·환경에 따라 행동은 크게 달라질 수 있어요.",
    instincts: {
      companion: "사람과 가까이 생활하도록 발달한 동반견 계열이에요. 짧은 교감과 예측 가능한 루틴이 동기가 됩니다.", social: "사람과 함께하는 활동에서 만족을 얻기 쉬운 사회적 동반견이에요.", puzzle: "신호를 빠르게 연결하고 문제를 푸는 과제에서 강점을 보일 수 있어요.", alert: "작은 소리와 움직임을 빨리 알아차리는 경계 성향이 놀이와 짖음에 나타날 수 있어요.", earth: "작은 동물을 찾고 쫓던 작업 배경이 있어 파기·추적·당기기 욕구가 나타날 수 있어요.", scent: "눈보다 코를 오래 쓰는 후각 작업 계열이라 냄새를 따라가는 활동이 강한 보상이 됩니다.", herding: "움직임을 관찰하고 통제하는 목양 작업 배경이 있어 멈춤과 방향 전환 과제가 잘 맞아요.", primitive: "독립적인 판단과 환경 관찰을 중시하는 스피츠·원시견 계열의 경향이 있어요.", retrieve: "물건을 입에 물고 운반해 사람에게 전달하도록 발달한 리트리버 계열이에요.", working: "사람과 함께 이동하고 역할을 수행해온 작업견 계열이라 목적 있는 활동이 중요해요.", individual: "품종 평균보다 이 강아지의 실제 선택을 관찰하는 것이 더 정확한 출발점이에요."
    },
    missions: {
      microTricks: "앉아→코 터치→매트 이동을 3회만 이어보세요. 짧게 끝내야 다음 참여가 좋아집니다.", socialCircuit: "보호자 따라오기→장난감 찾기→혼자 30초 놀기를 한 바퀴로 연결해보세요.", hideFind: "상자 3개 중 한 곳에 간식을 숨기고 위치를 매번 바꿔주세요.", soundSearch: "작은 소리가 나면 보호자를 보고, 바닥에 뿌린 간식 5개를 찾게 해주세요.", burrowBox: "수건을 느슨하게 말아 장난감을 숨기고 코와 앞발로 찾게 해주세요.", sniffTrail: "간식 조각으로 3m 냄새 길을 만든 뒤 마지막에 씹는 장난감을 놓아주세요.", treibball: "큰 공을 코로 밀어 표시한 장소까지 보내면 바로 칭찬해주세요.", choiceGame: "두 장난감을 바닥에 두고 스스로 고르게 한 뒤 선택한 것으로 5분간 놀아주세요.", tugRules: "‘시작’에 당기고 ‘놓아’에 멈추면 다시 시작하는 규칙을 5회 연습하세요.", coolShort: "서늘한 곳에서 3분 냄새 찾기→2분 휴식을 두 번 반복하세요.", fetchCarry: "가져오기→손 앞에 놓기→다른 장난감과 교환을 5번만 연습하세요.", workingWalk: "산책 중 5걸음 나란히 걷기→냄새 맡기 보상을 6번 반복하세요.", threeToyTest: "냄새 매트·당기기 로프·퍼즐 장난감을 놓고 첫 선택과 머문 시간을 기록하세요."
    },
    chews: {
      gentleSmall: "작은 입에 맞는 부드러운 고무와 얇은 직물 장난감을 번갈아 주세요. 뜯어지는 조각은 바로 치워주세요.", softRotation: "촉감이 다른 부드러운 장난감 3개를 하루씩 번갈아 새로움을 유지해주세요.", puzzleChew: "씹기 전에 굴리거나 열어야 보상이 나오는 퍼즐형 장난감이 지루함을 줄이는 데 유리해요.", scentChew: "냄새를 찾은 뒤 씹을 수 있게 순서를 만들어주세요. 코를 먼저 쓰면 가구로 향하는 탐색을 바꾸기 쉽습니다.", tugChew: "혼자 뜯는 장난감과 보호자와 당기는 로프를 구분해 ‘씹기 장소’를 명확히 해주세요.", independentChoice: "빼앗기보다 허용 장난감 두 개를 제시하고 스스로 교환하도록 기다려주세요.", flatFaceSafe: "입에 너무 크거나 호흡을 막는 형태는 피하고, 짧게 사용한 뒤 충분히 쉬게 해주세요.", carryChew: "삼키기 어려운 큰 크기의 운반용 장난감과 씹기용 장난감을 구분해 교환을 가르쳐주세요.", varietyTest: "부드러움·탄성·직물 세 촉감을 시험해 가장 오래 안전하게 머무는 재질을 찾아주세요."
    },
    cares: {
      dental: "작은 입은 치아가 촘촘하므로 장난감 크기와 잇몸 자극을 확인하고, 갑자기 한쪽으로만 씹으면 입안을 살펴주세요.", coat: "털 관리 시간이 스트레스가 되지 않도록 빗질 10초→보상→휴식을 반복해주세요.", back: "미끄러운 바닥과 반복적인 높은 점프를 줄이고, 냄새놀이는 허리를 과하게 비트는 좁은 공간을 피해주세요.", heat: "더운 날과 습한 날에는 짧고 서늘한 활동을 선택하고 거친 호흡이 길어지면 즉시 쉬게 해주세요.", escape: "문이 열리는 순간의 돌진을 막기 위해 현관에서 ‘기다림→허락’ 루틴을 매일 짧게 연습해주세요.", voice: "짖음을 혼내기보다 ‘알림→보호자 보기→매트’ 순서로 끝내는 신호를 가르쳐주세요.", earsWeight: "냄새 찾기 보상은 하루 급여량 안에서 사용하고, 산책 후에는 귀와 발 상태를 확인해주세요.", jointsWeight: "반복 점프보다 평지 걷기와 운반 놀이를 활용하고, 보상 간식은 하루 급여량에 포함해주세요.", herdingRest: "빛·그림자·사람 발을 계속 쫓는다면 흥분 놀이를 멈추고 매트에서 쉬는 신호를 먼저 연습해주세요.", observe: "7일 동안 첫 선택·집중 시간·싫어하는 촉감을 기록하면 품종명보다 유용한 맞춤 정보가 됩니다."
    }
  },
  en: {
    tendency: "Breed tendency", energy: "Activity drive", focus: "Task focus", independence: "Independent choice", low: "Low", high: "High", mission: "Today’s 10-minute mission", chew: "Chewing alternative", care: "Lifestyle checkpoint", sources: "Why this guide", close: "Close sources", note: "Breed is only a starting point. Age, experience, health and environment can create large differences within the same breed.",
    instincts: { companion: "A companion lineage shaped for close life with people; brief connection and predictable routines can motivate.", social: "A social companion often fulfilled by shared activity with people.", puzzle: "May excel at linking cues and solving changing problems.", alert: "Quick detection of small sounds and movement may appear in play and barking.", earth: "An earth-working background can surface as digging, tracking and tugging.", scent: "A scent-working lineage for which following odor can be a powerful reward.", herding: "A herding background favors movement control, stopping and directional tasks.", primitive: "Spitz and primitive-type tendencies may favor independent judgment and environmental scanning.", retrieve: "A retriever lineage shaped to carry objects and deliver them to people.", working: "A working lineage benefits from purposeful movement and a clear role.", individual: "Your dog’s real choices are a better starting point than a breed average." },
    missions: { microTricks: "Link sit, nose-touch and mat for only three rounds; finish while engagement is high.", socialCircuit: "Make a loop: follow you, find a toy, then play alone for 30 seconds.", hideFind: "Hide food in one of three boxes and change the position each round.", soundSearch: "After a small sound, reward looking at you, then scatter five treats to find.", burrowBox: "Loosely roll a towel around a toy and let nose and paws uncover it.", sniffTrail: "Make a 3 m food scent trail ending at an approved chew.", treibball: "Reward pushing a large ball with the nose toward a marked target.", choiceGame: "Offer two toys, let the dog choose, and play with that option for five minutes.", tugRules: "Practice five rounds: tug on ‘start,’ release on ‘drop,’ then restart.", coolShort: "In a cool place, repeat three minutes of scent search and two minutes of rest twice.", fetchCarry: "Practice bring, place by hand, and trade for another toy only five times.", workingWalk: "Repeat six cycles of five steps together followed by a sniffing reward.", threeToyTest: "Offer a snuffle mat, tug rope and puzzle; record first choice and time engaged." },
    chews: { gentleSmall: "Rotate soft rubber and thin fabric toys sized for a small mouth; remove loose pieces promptly.", softRotation: "Rotate three soft textures daily to preserve novelty.", puzzleChew: "A puzzle that must be rolled or opened before chewing can better address boredom.", scentChew: "Create a find-then-chew sequence so scent work redirects household searching.", tugChew: "Separate solo chews from interactive tug to make the approved chewing context clear.", independentChoice: "Offer two approved toys and wait for a voluntary trade instead of taking the item.", flatFaceSafe: "Avoid shapes that are oversized or obstruct breathing; keep sessions short with rest.", carryChew: "Use a large carry toy separate from the chew and teach a safe trade.", varietyTest: "Test soft, springy and fabric textures; keep the one that earns the longest safe engagement." },
    cares: { dental: "Check size and gum contact for a crowded small mouth; inspect if chewing suddenly shifts to one side.", coat: "Make grooming predictable: brush 10 seconds, reward, then pause.", back: "Reduce slippery floors and repeated high jumps; avoid tight twisting search spaces.", heat: "Choose short, cool activities in heat or humidity and rest immediately if heavy breathing persists.", escape: "Practice a brief wait-then-release routine at the door every day.", voice: "Teach a clear finish to alerts: notice, look at you, then go to mat.", earsWeight: "Count search rewards within the daily ration and check ears and paws after walks.", jointsWeight: "Favor level walks and carrying over repeated jumps; count rewards in the daily ration.", herdingRest: "If light, shadows or feet are chased repeatedly, lower arousal and teach settling on a mat.", observe: "Record first choice, engagement time and disliked texture for seven days; it is more useful than a label." }
  },
  zh: {
    tendency: "犬种倾向", energy: "活动需求", focus: "任务专注", independence: "独立选择", low: "低", high: "高", mission: "今日10分钟任务", chew: "啃咬替代策略", care: "生活检查重点", sources: "指南依据", close: "收起依据", note: "犬种只是起点。同一犬种也会因年龄、经历、健康和环境而有很大差异。",
    instincts: { companion: "为与人亲近生活而发展的伴侣犬，短暂互动和可预测日程更有动力。", social: "容易从与人共同活动中获得满足的社交型伴侣犬。", puzzle: "可能擅长连接信号和解决变化的问题。", alert: "对细小声音和动作敏感，可能表现为游戏兴奋或吠叫。", earth: "地下工作背景可能表现为挖掘、追踪和拉扯。", scent: "嗅觉工作犬，追随气味本身就是强烈奖励。", herding: "牧群工作背景适合控制移动、停止和转向任务。", primitive: "尖嘴犬及原始犬型更倾向独立判断和观察环境。", retrieve: "寻回犬擅长用嘴搬运物品并交给人。", working: "工作犬需要有目的的移动和清晰任务。", individual: "比犬种平均更应观察这只狗的真实选择。" },
    missions: { microTricks: "只做三轮：坐下—碰鼻—回垫子，在兴趣高时结束。", socialCircuit: "连接成一圈：跟随主人—寻找玩具—独自玩30秒。", hideFind: "在三个盒子之一藏食物，每轮改变位置。", soundSearch: "出现小声音时先看主人，再寻找散在地上的5颗零食。", burrowBox: "用毛巾松松包住玩具，让它用鼻子和前爪寻找。", sniffTrail: "用零食做3米气味路线，终点放可啃咬玩具。", treibball: "用鼻子把大球推到标记地点后立即奖励。", choiceGame: "放两个玩具让它自己选择，并用所选玩具玩5分钟。", tugRules: "练习5轮：听到开始后拉扯，听到放下后停止，再重新开始。", coolShort: "在凉爽处进行3分钟嗅闻、2分钟休息，重复两次。", fetchCarry: "只练5次：取回—放到手前—与另一玩具交换。", workingWalk: "重复6次：并排走5步后获得嗅闻奖励。", threeToyTest: "提供嗅闻垫、拉绳和益智玩具，记录首选和停留时间。" },
    chews: { gentleSmall: "轮换适合小嘴的软橡胶和薄布玩具，发现碎片立即清理。", softRotation: "每天轮换三种柔软触感，保持新鲜感。", puzzleChew: "需要先滚动或打开才能获得奖励的益智啃咬玩具有助于减少无聊。", scentChew: "建立先寻找后啃咬的顺序，让嗅闻转移对家具的探索。", tugChew: "区分独自啃咬玩具和与主人拉扯的绳子，明确可啃咬场景。", independentChoice: "不要抢夺，提供两个允许的玩具并等待它主动交换。", flatFaceSafe: "避免过大或影响呼吸的形状，短时间使用并充分休息。", carryChew: "使用不易吞咽的大型搬运玩具，与啃咬玩具分开并训练交换。", varietyTest: "测试柔软、弹性和布料三种触感，保留安全互动时间最长的一种。" },
    cares: { dental: "小嘴牙齿较密，应检查玩具尺寸与牙龈刺激；突然只用一侧咀嚼时查看口腔。", coat: "把梳毛变得可预测：梳10秒—奖励—休息。", back: "减少湿滑地面和反复高跳，嗅闻游戏避免狭窄扭腰空间。", heat: "炎热潮湿时选择短暂凉爽活动，粗重呼吸持续时立即休息。", escape: "每天在门口短练“等待—允许”流程，防止开门冲出。", voice: "不要责骂吠叫，训练“提醒—看主人—回垫子”的结束信号。", earsWeight: "寻找游戏的零食计入每日食量，散步后检查耳朵和脚掌。", jointsWeight: "以平地行走和搬运游戏代替反复跳跃，奖励计入每日食量。", herdingRest: "若反复追光影或脚步，应降低兴奋并先练习在垫子上休息。", observe: "连续7天记录首选、专注时间和不喜欢的触感，比犬种名称更有用。" }
  },
  ja: {
    tendency: "犬種傾向", energy: "活動欲求", focus: "課題集中", independence: "自立選択", low: "低", high: "高", mission: "今日の10分ミッション", chew: "噛み替え戦略", care: "生活チェック", sources: "ガイドの根拠", close: "根拠を閉じる", note: "犬種は出発点にすぎません。同じ犬種でも年齢・経験・健康・環境で行動は大きく異なります。",
    instincts: { companion: "人と近く暮らすために発達した伴侶犬。短い交流と予測できる日課が動機になります。", social: "人との共同活動で満足しやすい社交的な伴侶犬です。", puzzle: "合図を結びつけ、変化する問題を解く課題が得意な傾向。", alert: "小さな音や動きにすぐ気づき、遊びや吠えに表れることがあります。", earth: "地中作業の背景が、掘る・追う・引っ張る欲求として表れます。", scent: "嗅覚作業の系統で、匂いを追うこと自体が強い報酬です。", herding: "牧畜作業の背景があり、動きの制御・停止・方向転換が向きます。", primitive: "スピッツ・原始犬タイプは、自立判断と環境観察を重視する傾向。", retrieve: "物を口で運び、人へ届けるために発達したレトリーバー系です。", working: "人と移動し役割を果たしてきた作業犬で、目的ある活動が重要。", individual: "犬種平均より、その子の実際の選択を見る方が正確です。" },
    missions: { microTricks: "お座り→鼻タッチ→マットを3周だけ。意欲が高いうちに終えます。", socialCircuit: "飼い主について行く→玩具を探す→30秒ひとり遊びを一周にします。", hideFind: "3つの箱の1つにフードを隠し、毎回場所を変えます。", soundSearch: "小さな音の後に飼い主を見たら、床のフード5粒を探します。", burrowBox: "タオルを緩く巻いて玩具を隠し、鼻と前足で探します。", sniffTrail: "3mの匂い道を作り、最後に許可した噛む玩具を置きます。", treibball: "大きなボールを鼻で印まで押したらすぐ褒めます。", choiceGame: "2つの玩具から自分で選ばせ、選んだ玩具で5分遊びます。", tugRules: "『開始』で引き、『離して』で止め、再開する流れを5回。", coolShort: "涼しい場所で3分匂い探し→2分休憩を2回。", fetchCarry: "持ってくる→手前に置く→別の玩具と交換を5回だけ。", workingWalk: "5歩並んで歩く→匂い嗅ぎの報酬を6回繰り返します。", threeToyTest: "ノーズマット・ロープ・パズルを置き、最初の選択と時間を記録します。" },
    chews: { gentleSmall: "小さな口に合う柔らかいゴムと薄い布玩具を交互に。破片はすぐ除きます。", softRotation: "柔らかさの違う3つの玩具を日替わりで使い、新鮮さを保ちます。", puzzleChew: "転がす・開けると報酬が出るパズル型が退屈対策に向きます。", scentChew: "探した後に噛む順番を作り、家具への探索を匂い活動へ移します。", tugChew: "ひとり噛みと人とのロープ遊びを分け、許可された場所を明確にします。", independentChoice: "奪わず、許可した2つを提示して自発的な交換を待ちます。", flatFaceSafe: "大きすぎたり呼吸を妨げる形を避け、短時間で十分に休みます。", carryChew: "飲み込みにくい大きな運搬玩具と噛む玩具を分け、安全な交換を教えます。", varietyTest: "柔らかい・弾む・布の3触感を試し、安全に長く使う素材を選びます。" },
    cares: { dental: "小さな口は歯が密集しやすいため、サイズと歯ぐき刺激を確認。片側噛みが急に増えたら口を見ます。", coat: "ブラッシング10秒→報酬→休憩で予測できるケアにします。", back: "滑る床と高い反復ジャンプを減らし、腰をひねる狭い探索場所を避けます。", heat: "暑さと湿気では短く涼しい活動を選び、荒い呼吸が続けばすぐ休みます。", escape: "玄関で『待つ→許可』を毎日短く練習します。", voice: "吠えを叱らず、『知らせる→飼い主を見る→マット』で終了を教えます。", earsWeight: "探索の報酬は一日の食事量に含め、散歩後は耳と足を確認します。", jointsWeight: "反復ジャンプより平地歩行と運搬遊び。報酬は一日の食事量に含めます。", herdingRest: "光・影・足を追い続けるなら興奮を下げ、マットで休む合図を先に練習します。", observe: "7日間、最初の選択・集中時間・嫌う触感を記録すると犬種名より役立ちます。" }
  }
} as const;
