import type { LangKey } from "./breed-guides";

export type QuizItem = {
  question: string;
  answer: boolean;
  explanation: string;
};

export const quizFeedback: Record<LangKey, { correct: string; wrong: string; answer: string; trueLabel: string; falseLabel: string }> = {
  ko: { correct: "정답이에요!", wrong: "아쉬워요. 다시 기억해두세요!", answer: "정답", trueLabel: "그렇다", falseLabel: "아니다" },
  en: { correct: "Correct!", wrong: "Not quite. Save this one for next time!", answer: "Answer", trueLabel: "True", falseLabel: "False" },
  zh: { correct: "答对了！", wrong: "差一点，请记住这个答案！", answer: "答案", trueLabel: "是", falseLabel: "否" },
  ja: { correct: "正解です！", wrong: "惜しい！次のために覚えておきましょう。", answer: "正解", trueLabel: "そう思う", falseLabel: "違う" },
};

export const quizBank: Record<LangKey, QuizItem[]> = {
  ko: [
    { question: "같은 견종이면 성격도 거의 같을까요?", answer: false, explanation: "견종은 힌트일 뿐, 경험·환경·현재 감정에 따라 개체차가 크게 나타납니다." },
    { question: "으르렁거림은 무조건 나쁜 행동일까요?", answer: false, explanation: "으르렁거림은 불편함을 알리는 중요한 경고 신호입니다. 억누르기보다 원인과 거리를 살펴야 합니다." },
    { question: "하품이 긴장 신호일 때도 있을까요?", answer: true, explanation: "졸리지 않은 상황의 하품은 긴장을 낮추려는 신호일 수 있습니다." },
    { question: "꼬리를 흔들면 언제나 기분이 좋은 걸까요?", answer: false, explanation: "꼬리의 높이·속도와 몸의 긴장을 함께 봐야 합니다. 흥분이나 경계 때도 꼬리를 흔듭니다." },
    { question: "짧게 냄새를 맡으며 산책하는 것도 충분한 두뇌 활동이 될까요?", answer: true, explanation: "여러 냄새를 구별하고 따라가는 활동은 짧은 시간에도 집중력을 사용하며 정서적 만족에 도움이 됩니다." },
    { question: "한참 뒤에 혼내도 강아지는 이유를 알까요?", answer: false, explanation: "강아지는 바로 이어진 결과를 더 쉽게 연결합니다. 시간이 지난 꾸중은 무엇을 고쳐야 하는지 알려주기 어렵습니다." },
    { question: "이갈이 시기에는 씹는 행동이 늘 수 있을까요?", answer: true, explanation: "치아 교체기의 불편함과 탐색 욕구로 씹는 행동이 늘 수 있어 안전한 대체물이 필요합니다." },
    { question: "강아지가 겁을 먹고 몸이 굳으면, 무서워하는 대상에 가까이 데려가야 할까요?", answer: false, explanation: "몸이 굳는 반응은 두려움 신호일 수 있습니다. 거리를 확보하고 스스로 선택할 시간을 주는 편이 안전합니다." },
    { question: "올바른 행동 직후 칭찬하면 학습이 빨라질까요?", answer: true, explanation: "행동 직후의 보상은 어떤 선택이 좋았는지 명확하게 알려줍니다." },
    { question: "성견의 행동이 갑자기 달라졌다면 건강 상태를 확인해야 할까요?", answer: true, explanation: "통증·치아·소화기 문제가 예민함이나 물어뜯는 행동으로 나타날 수 있어, 갑작스러운 변화에는 건강 확인이 우선입니다." },
    { question: "사회화는 최대한 많은 강아지를 만나는 것일까요?", answer: false, explanation: "사회화의 핵심은 숫자가 아니라 안전하고 긍정적인 경험입니다. 억지 만남은 오히려 부담이 됩니다." },
    { question: "손님이 올 때 안전한 휴식 공간이 도움이 될까요?", answer: true, explanation: "스스로 물러날 수 있는 고정된 자리는 방문 상황의 긴장을 낮추는 데 도움이 됩니다." },
    { question: "쓴맛 스티커만 붙이면 씹고 싶은 욕구도 사라질까요?", answer: false, explanation: "쓴맛은 금지 표면의 경계를 돕는 보조수단입니다. 환경 관리와 안전한 대체 씹기를 함께 제공해야 합니다." },
    { question: "견종만으로 강아지의 공격·물기 행동을 정확히 예측할 수 있을까요?", answer: false, explanation: "개별 경험·사회화·건강·생활 환경을 함께 살펴야 하며, 견종만으로 정확하게 예측할 수는 없습니다." },
    { question: "신나게 놀고 난 뒤에는 잠시 쉬는 것이 도움이 될까요?", answer: true, explanation: "물 마시기·매트에서 쉬기·차분하게 씹기처럼 일정한 진정 순서를 만들면 흥분을 가라앉히는 연습이 됩니다." },
    { question: "물어뜯으려는 순간 안전한 장난감으로 바꿔주면 도움이 될까요?", answer: true, explanation: "금지 행동만 막기보다 씹어도 되는 대상을 바로 연결하고 선택한 순간 칭찬하면 대체 행동을 배우기 쉽습니다." },
    { question: "전선은 한 줄만 가늘게 가려도 충분히 보호될까요?", answer: false, explanation: "노출된 면과 끝부분이 남으면 다시 접근할 수 있습니다. 전원을 분리하고 접근을 막은 뒤, 필요한 범위를 넓게 보호해야 합니다." },
    { question: "산책 시간만 늘리면 모든 물어뜯기 행동이 해결될까요?", answer: false, explanation: "물어뜯기는 이갈이·불안·지루함·통증·환경 등 원인이 다양합니다. 활동량과 함께 원인과 상황을 살펴야 합니다." },
    { question: "강아지가 편안할 때는 입 주변과 몸의 힘도 부드러워질까요?", answer: true, explanation: "한 가지 신호보다 눈·입·귀·몸의 긴장을 함께 살펴야 하며, 편안할 때는 전반적인 움직임이 부드러워지는 편입니다." },
    { question: "붙인 스티커 끝이 들뜨면 장난감처럼 물 수 있을까요?", answer: true, explanation: "들뜬 끝은 잡아당기기 좋은 부분이 될 수 있습니다. 넓게 밀착하고 끝부분까지 꼭 눌러주세요." },
  ],
  en: [
    { question: "Do dogs of the same breed have almost the same personality?", answer: false, explanation: "Breed is only a clue. Experience, environment and current emotion create large individual differences." },
    { question: "Is growling always bad behavior?", answer: false, explanation: "Growling is valuable communication about discomfort. Look at the cause and distance instead of suppressing the warning." },
    { question: "Can yawning be a sign of tension?", answer: true, explanation: "When a dog is not sleepy, yawning can be an attempt to reduce tension." },
    { question: "Does a wagging tail always mean a happy dog?", answer: false, explanation: "Read tail height and speed with the whole body. Dogs also wag when excited or guarded." },
    { question: "Can a short sniff walk tire the brain?", answer: true, explanation: "Choosing and tracking scents uses focus and can provide emotional satisfaction even in a short session." },
    { question: "Will a dog understand punishment long after the event?", answer: false, explanation: "Dogs connect immediate consequences more easily. Delayed scolding does not clearly show what should change." },
    { question: "Can chewing increase during teething?", answer: true, explanation: "Tooth changes and exploration can increase chewing, so safe alternatives are important." },
    { question: "Should a frozen dog be pushed closer to the scary thing?", answer: false, explanation: "Freezing can signal fear. Create distance and allow time for a voluntary choice." },
    { question: "Does praise right after a good choice speed learning?", answer: true, explanation: "An immediate reward clearly marks which choice worked." },
    { question: "Does a sudden behavior change in an adult dog need a health check?", answer: true, explanation: "Pain, dental or digestive issues can look like irritability or chewing. Check health first when change is sudden." },
    { question: "Does socialization mean meeting as many dogs as possible?", answer: false, explanation: "Quality matters more than quantity. Safe, positive experiences help more than forced greetings." },
    { question: "Can a safe resting place help when visitors arrive?", answer: true, explanation: "A fixed place where the dog can retreat by choice can lower tension around visitors." },
    { question: "Do bitter stickers remove the need to chew by themselves?", answer: false, explanation: "Bitter taste only supports a surface boundary. Pair it with access management and an approved chew." },
    { question: "Can breed alone accurately predict an individual dog’s bite risk?", answer: false, explanation: "Individual history, socialization, health and management environment must be considered together." },
    { question: "Can a short rest help after exciting play?", answer: true, explanation: "A consistent cool-down routine with water, a mat and calm chewing helps dogs practice recovery." },
    { question: "Can redirecting to a safe toy help at the moment chewing starts?", answer: true, explanation: "Connecting an approved chew and praising the choice teaches an alternative more clearly than only blocking the behavior." },
    { question: "Is covering a cable with one thin strip enough protection?", answer: false, explanation: "Exposed surfaces and loose ends remain accessible. Disconnect power, prevent access and protect the necessary area broadly." },
    { question: "Will longer walks solve every chewing problem?", answer: false, explanation: "Chewing may relate to teething, anxiety, boredom, pain or the environment. Activity helps, but the context and cause still matter." },
    { question: "When a dog is comfortable, do the mouth and body usually look softer?", answer: true, explanation: "Read the eyes, mouth, ears and body together. Comfortable dogs generally move with less overall tension." },
    { question: "Can a lifted sticker edge become tempting to grab?", answer: true, explanation: "A loose edge can feel like something to pull. Attach the sticker flat and press every edge firmly." },
  ],
  zh: [
    { question: "同一犬种的狗狗，性格也几乎一样吗？", answer: false, explanation: "犬种只是线索，经历、环境和当下情绪会造成很大的个体差异。" },
    { question: "低吼一定是坏行为吗？", answer: false, explanation: "低吼是在表达不适的重要警告。应观察原因和距离，而不是压制信号。" },
    { question: "打哈欠有时也是紧张信号吗？", answer: true, explanation: "不困时打哈欠，可能是在尝试降低紧张。" },
    { question: "摇尾巴总是代表开心吗？", answer: false, explanation: "要结合尾巴高度、速度和全身状态判断，兴奋或警戒时也会摇尾巴。" },
    { question: "短时间的嗅闻散步也会让大脑疲劳吗？", answer: true, explanation: "选择和追踪气味需要专注，即使时间短也能带来情绪满足。" },
    { question: "事情过去很久后责备，狗狗也能理解原因吗？", answer: false, explanation: "狗狗更容易连接紧接着发生的结果，延迟责备很难说明应改变什么。" },
    { question: "换牙期啃咬行为会增加吗？", answer: true, explanation: "牙齿变化的不适和探索欲会增加啃咬，需要提供安全替代物。" },
    { question: "狗狗僵住时应该推它靠近害怕的东西吗？", answer: false, explanation: "僵住可能是恐惧信号，应拉开距离并给它自主选择的时间。" },
    { question: "正确行为后立即表扬会加快学习吗？", answer: true, explanation: "即时奖励能清楚告诉狗狗哪一个选择是正确的。" },
    { question: "成年犬突然改变行为需要先检查健康吗？", answer: true, explanation: "疼痛、牙齿或消化问题也可能表现为敏感或啃咬，突然变化应先检查健康。" },
    { question: "社会化就是尽量多见其他狗狗吗？", answer: false, explanation: "关键不是数量，而是安全且积极的体验，强迫见面反而会造成压力。" },
    { question: "来客时准备安全休息区会有帮助吗？", answer: true, explanation: "能自主退回的固定位置有助于降低来客时的紧张。" },
    { question: "只贴苦味贴就能消除啃咬欲望吗？", answer: false, explanation: "苦味只是帮助建立禁咬表面的边界，还要配合环境管理和安全替代物。" },
    { question: "只凭犬种能准确预测单只狗的咬人风险吗？", answer: false, explanation: "还要综合个体经历、社会化、健康和管理环境，不能只凭犬种判断。" },
    { question: "兴奋玩耍后短暂休息会有帮助吗？", answer: true, explanation: "喝水、上垫子和安静啃咬等固定冷静流程有助于练习恢复。" },
    { question: "开始乱咬时立刻换成安全玩具有帮助吗？", answer: true, explanation: "不仅阻止行为，还要马上提供可啃咬物，并在选对时表扬，这样更容易学会替代行为。" },
    { question: "电线只用一条窄贴遮住就足够安全吗？", answer: false, explanation: "裸露表面和翘起边缘仍可接触。先断电并阻止靠近，再宽范围保护需要覆盖的位置。" },
    { question: "只延长散步时间就能解决所有啃咬问题吗？", answer: false, explanation: "啃咬可能与换牙、焦虑、无聊、疼痛或环境有关，除了活动量还要观察原因和情境。" },
    { question: "狗狗放松时，嘴部和身体也会显得更柔和吗？", answer: true, explanation: "要综合观察眼睛、嘴、耳朵和身体；放松时整体动作通常更柔和。" },
    { question: "贴纸边缘翘起时，会像玩具一样吸引狗狗去咬吗？", answer: true, explanation: "翘起的边缘容易被拉扯。请宽幅贴合，并将所有边缘压紧。" },
  ],
  ja: [
    { question: "同じ犬種なら性格もほぼ同じでしょうか？", answer: false, explanation: "犬種はヒントの一つ。経験・環境・今の感情によって大きな個体差があります。" },
    { question: "うなるのは必ず悪い行動でしょうか？", answer: false, explanation: "うなりは不快感を伝える大切な警告です。抑えるより原因と距離を確認します。" },
    { question: "あくびが緊張のサインになることもありますか？", answer: true, explanation: "眠くない場面のあくびは、緊張を下げようとするサインの場合があります。" },
    { question: "しっぽを振ればいつも喜んでいるのでしょうか？", answer: false, explanation: "高さ・速さと全身の緊張を合わせて見ます。興奮や警戒でも振ることがあります。" },
    { question: "短いにおい散歩でも頭は疲れますか？", answer: true, explanation: "においを選び追う活動は集中力を使い、短時間でも心の満足につながります。" },
    { question: "時間がたってから叱っても理由は分かりますか？", answer: false, explanation: "犬は直後の結果を結びつけやすく、遅い叱責では何を変えるべきか伝わりにくいです。" },
    { question: "歯の生え変わり時期は噛む行動が増えますか？", answer: true, explanation: "歯の違和感と探索欲で噛む行動が増えるため、安全な代替物が必要です。" },
    { question: "犬が固まったら怖い物へ近づけるべきですか？", answer: false, explanation: "固まるのは恐怖のサインかもしれません。距離と自分で選ぶ時間を与えます。" },
    { question: "良い行動の直後に褒めると学習が早まりますか？", answer: true, explanation: "直後の報酬は、どの選択が良かったかを明確に伝えます。" },
    { question: "成犬の急な行動変化は健康確認が必要ですか？", answer: true, explanation: "痛み・歯・消化器の問題も敏感さや噛み行動に見えるため、急な変化は健康確認が先です。" },
    { question: "社会化はできるだけ多くの犬に会うことですか？", answer: false, explanation: "数より安全で良い経験が重要です。無理な挨拶はかえって負担になります。" },
    { question: "来客時に安全な休憩場所があると役立ちますか？", answer: true, explanation: "自分で離れられる定位置は、来客時の緊張を下げる助けになります。" },
    { question: "苦味ステッカーだけで噛みたい欲求も消えますか？", answer: false, explanation: "苦味は禁じる面の境界を助ける補助です。環境管理と安全な代替噛みを組み合わせます。" },
    { question: "犬種だけで一頭の噛む危険を正確に予測できますか？", answer: false, explanation: "個体の経験・社会化・健康・管理環境を合わせて見る必要があります。" },
    { question: "興奮した遊びの後は短い休憩が役立ちますか？", answer: true, explanation: "水・マット・静かに噛むという一定の手順は、興奮から回復する練習になります。" },
    { question: "噛み始めた瞬間に安全なおもちゃへ替えると役立ちますか？", answer: true, explanation: "禁止するだけでなく、噛んでよい物を示し、選べた瞬間に褒めると代替行動を学びやすくなります。" },
    { question: "コードは細い一列だけ覆えば十分に守れますか？", answer: false, explanation: "露出面や浮いた端が残ると再び触れられます。電源を外し、接近を防いだ上で必要な範囲を広く守ります。" },
    { question: "散歩時間を延ばすだけですべての噛み癖は解決しますか？", answer: false, explanation: "歯の生え変わり、不安、退屈、痛み、環境など原因はさまざまです。活動量と一緒に原因と場面を確認します。" },
    { question: "犬がリラックスしている時は口元や体の力も柔らかくなりますか？", answer: true, explanation: "目・口・耳・体を合わせて見ます。安心している時は全体の動きが柔らかくなる傾向があります。" },
    { question: "ステッカーの端が浮くと、おもちゃのように噛むことがありますか？", answer: true, explanation: "浮いた端は引っ張りやすい部分になります。広く密着させ、端までしっかり押さえてください。" },
  ],
};
